name: Node.js CI
on: [push]
jobs:
  front-end:
    strategy:
      matrix:
        script: [build, test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache react node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules-react
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: react-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            react-${{ runner.os }}-build-${{ env.cache-name }}-
            react-${{ runner.os }}-build-
            react-${{ runner.os }}-
      - name: Install dependencies
        run: npm install

      - name: Run Script
        run: npm run ${{ matrix.script }}